export const MEXICAN_STATES = [
  'Aguascalientes',
  'Baja California',
  'Baja California Sur',
  'Campeche',
  'Chiapas',
  'Chihuahua',
  'Ciudad de México',
  'Coahuila',
  'Colima',
  'Durango',
  'Estado de México',
  'Guanajuato',
  'Guerrero',
  'Hidalgo',
  'Jalisco',
  'Michoacán',
  'Morelos',
  'Nayarit',
  'Nuevo León',
  'Oaxaca',
  'Puebla',
  'Querétaro',
  'Quintana Roo',
  'San Luis Potosí',
  'Sinaloa',
  'Sonora',
  'Tabasco',
  'Tamaulipas',
  'Tlaxcala',
  'Veracruz',
  'Yucatán',
  'Zacatecas',
];

export const MEXICAN_CITIES_BY_STATE: Record<string, string[]> = {
  'Aguascalientes': ['Aguascalientes', 'Jesús María', 'Calvillo', 'Rincón de Romos', 'Pabellón de Arteaga', 'San Francisco de los Romo', 'Cosío', 'Asientos', 'Otra localidad'],
  'Baja California': ['Tijuana', 'Mexicali', 'Ensenada', 'Playas de Rosarito', 'Tecate', 'San Quintín', 'San Felipe', 'Otra localidad'],
  'Baja California Sur': ['La Paz', 'Los Cabos', 'San José del Cabo', 'Cabo San Lucas', 'Ciudad Constitución', 'Loreto', 'Santa Rosalía', 'Otra localidad'],
  'Campeche': ['San Francisco de Campeche', 'Ciudad del Carmen', 'Champotón', 'Escárcega', 'Calkiní', 'Hecelchakán', 'Candelaria', 'Otra localidad'],
  'Chiapas': ['Tuxtla Gutiérrez', 'Tapachula', 'San Cristóbal de las Casas', 'Comitán de Domínguez', 'Palenque', 'Chiapa de Corzo', 'Tonalá', 'Ocosingo', 'Villaflores', 'Otra localidad'],
  'Chihuahua': ['Chihuahua', 'Ciudad Juárez', 'Cuauhtémoc', 'Delicias', 'Hidalgo del Parral', 'Nuevo Casas Grandes', 'Camargo', 'Meoqui', 'Guachochi', 'Otra localidad'],
  'Ciudad de México': ['Cuauhtémoc', 'Miguel Hidalgo', 'Benito Juárez', 'Coyoacán', 'Álvaro Obregón', 'Tlalpan', 'Iztapalapa', 'Gustavo A. Madero', 'Venustiano Carranza', 'Azcapotzalco', 'Iztacalco', 'Cuajimalpa', 'Xochimilco', 'Tláhuac', 'Magdalena Contreras', 'Milpa Alta', 'Otra alcaldía'],
  'Coahuila': ['Saltillo', 'Torreón', 'Monclova', 'Piedras Negras', 'Acuña', 'Matamoros', 'Ramos Arizpe', 'Sabinas', 'Frontera', 'Otra localidad'],
  'Colima': ['Colima', 'Manzanillo', 'Tecomán', 'Villa de Álvarez', 'Armería', 'Comala', 'Coquimatlán', 'Cuauhtémoc', 'Otra localidad'],
  'Durango': ['Durango', 'Gómez Palacio', 'Lerdo', 'Santiago Papasquiaro', 'El Salto', 'Canatlán', 'Guadalupe Victoria', 'Pueblo Nuevo', 'Otra localidad'],
  'Estado de México': ['Toluca', 'Ecatepec', 'Naucalpan', 'Tlalnepantla', 'Nezahualcóyotl', 'Cuautitlán Izcalli', 'Chimalhuacán', 'Metepec', 'Atizapán de Zaragoza', 'Huixquilucan', 'Coacalco', 'Texcoco', 'Chalco', 'Valle de Chalco', 'Los Reyes La Paz', 'Zinacantepec', 'Tecámac', 'Otra localidad'],
  'Guanajuato': ['León', 'Irapuato', 'Celaya', 'Salamanca', 'Guanajuato', 'San Miguel de Allende', 'Silao', 'Dolores Hidalgo', 'San Francisco del Rincón', 'Cortazar', 'Acámbaro', 'Valle de Santiago', 'Otra localidad'],
  'Guerrero': ['Acapulco de Juárez', 'Chilpancingo de los Bravo', 'Zihuatanejo', 'Iguala de la Independencia', 'Taxco de Alarcón', 'Tlapa de Comonfort', 'Tecpan de Galeana', 'Ometepec', 'Otra localidad'],
  'Hidalgo': ['Pachuca de Soto', 'Tulancingo de Bravo', 'Tula de Allende', 'Mineral de la Reforma', 'Tizayuca', 'Huejutla de Reyes', 'Tepeji del Río', 'Actopan', 'Ixmiquilpan', 'Apan', 'Otra localidad'],
  'Jalisco': ['Guadalajara', 'Zapopan', 'Tlaquepaque', 'Tonalá', 'Tlajomulco de Zúñiga', 'Puerto Vallarta', 'Lagos de Moreno', 'Tepatitlán de Morelos', 'Ciudad Guzmán', 'El Salto', 'Ocotlán', 'Arandas', 'Ameca', 'Otra localidad'],
  'Michoacán': ['Morelia', 'Uruapan', 'Zamora', 'Lázaro Cárdenas', 'Zitácuaro', 'Apatzingán', 'La Piedad', 'Pátzcuaro', 'Sahuayo', 'Hidalgo', 'Maravatío', 'Jacona', 'Otra localidad'],
  'Morelos': ['Cuernavaca', 'Jiutepec', 'Cuautla', 'Temixco', 'Emiliano Zapata', 'Yautepec', 'Ayala', 'Xochitepec', 'Zacatepec', 'Jojutla', 'Tepoztlán', 'Otra localidad'],
  'Nayarit': ['Tepic', 'Bahía de Banderas', 'Xalisco', 'Compostela', 'Santiago Ixcuintla', 'Ixtlán del Río', 'Tuxpan', 'San Blas', 'Tecuala', 'Acaponeta', 'Otra localidad'],
  'Nuevo León': ['Monterrey', 'Guadalupe', 'San Nicolás de los Garza', 'San Pedro Garza García', 'Apodaca', 'General Escobedo', 'Santa Catarina', 'Juárez', 'García', 'Cadereyta Jiménez', 'Santiago', 'Linares', 'Montemorelos', 'Otra localidad'],
  'Oaxaca': ['Oaxaca de Juárez', 'San Juan Bautista Tuxtepec', 'Salina Cruz', 'Juchitán de Zaragoza', 'Santa Cruz Xoxocotlán', 'Santo Domingo Tehuantepec', 'Huajuapan de León', 'San Pedro Pochutla', 'Santa María Huatulco', 'Puerto Escondido', 'Miahuatlán', 'Otra localidad'],
  'Puebla': ['Puebla', 'Tehuacán', 'San Martín Texmelucan', 'San Andrés Cholula', 'San Pedro Cholula', 'Atlixco', 'Teziutlán', 'Amozoc', 'Huauchinango', 'Cuautlancingo', 'Tepeaca', 'Zacatlán', 'Izúcar de Matamoros', 'Otra localidad'],
  'Querétaro': ['Santiago de Querétaro', 'San Juan del Río', 'Corregidora', 'El Marqués', 'Cadereyta de Montes', 'Tequisquiapan', 'Pedro Escobedo', 'Ezequiel Montes', 'Colón', 'Jalpan de Serra', 'Otra localidad'],
  'Quintana Roo': ['Cancún (Benito Juárez)', 'Playa del Carmen (Solidaridad)', 'Chetumal (Othón P. Blanco)', 'Cozumel', 'Tulum', 'Isla Mujeres', 'Felipe Carrillo Puerto', 'Puerto Morelos', 'Bacalar', 'Otra localidad'],
  'San Luis Potosí': ['San Luis Potosí', 'Soledad de Graciano Sánchez', 'Ciudad Valles', 'Matehuala', 'Rioverde', 'Tamazunchale', 'Cerritos', 'Ciudad Fernández', 'Ébano', 'Charcas', 'Otra localidad'],
  'Sinaloa': ['Culiacán', 'Mazatlán', 'Los Mochis (Ahome)', 'Guasave', 'Guamúchil (Salvador Alvarado)', 'Navolato', 'El Fuerte', 'Escuinapa', 'Costa Rica', 'El Rosario', 'Otra localidad'],
  'Sonora': ['Hermosillo', 'Ciudad Obregón (Cajeme)', 'Nogales', 'San Luis Río Colorado', 'Navojoa', 'Guaymas', 'Agua Prieta', 'Caborca', 'Empalme', 'Puerto Peñasco', 'Cananea', 'Huatabampo', 'Otra localidad'],
  'Tabasco': ['Villahermosa (Centro)', 'Cárdenas', 'Comalcalco', 'Huimanguillo', 'Macuspana', 'Cunduacán', 'Paraíso', 'Teapa', 'Jalpa de Méndez', 'Nacajuca', 'Frontera (Centla)', 'Tenosique', 'Otra localidad'],
  'Tamaulipas': ['Reynosa', 'Matamoros', 'Nuevo Laredo', 'Ciudad Victoria', 'Tampico', 'Ciudad Madero', 'Miramar', 'Altamira', 'El Mante', 'Río Bravo', 'Valle Hermoso', 'San Fernando', 'Otra localidad'],
  'Tlaxcala': ['Tlaxcala', 'Apizaco', 'Chiautempan', 'Huamantla', 'San Pablo del Monte', 'Zacatelco', 'Calpulalpan', 'Contla', 'Santa Ana Chiautempan', 'Papalotla', 'Otra localidad'],
  'Veracruz': ['Veracruz', 'Xalapa', 'Coatzacoalcos', 'Poza Rica de Hidalgo', 'Córdoba', 'Minatitlán', 'Boca del Río', 'Orizaba', 'Tuxpan', 'San Andrés Tuxtla', 'Papantla', 'Cosoleacaque', 'Martínez de la Torre', 'Tierra Blanca', 'Fortín', 'Otra localidad'],
  'Yucatán': ['Mérida', 'Kanasín', 'Valladolid', 'Tizimín', 'Umán', 'Progreso', 'Ticul', 'Tekax', 'Motul', 'Hunucmá', 'Izamal', 'Oxkutzcab', 'Otra localidad'],
  'Zacatecas': ['Zacatecas', 'Guadalupe', 'Fresnillo', 'Jerez de García Salinas', 'Río Grande', 'Sombrerete', 'Calera', 'Ojocaliente', 'Loreto', 'Tlaltenango', 'Pinos', 'Jalpa', 'Nochistlán', 'Otra localidad'],
};

export function getCitiesForState(state: string): string[] {
  return MEXICAN_CITIES_BY_STATE[state] || ['Otra localidad'];
}
